
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgqtbzwlzbgraefgbffo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNncXRiendsemJncmFlZmdiZmZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MDE3MzIsImV4cCI6MjA1OTk3NzczMn0.g1kJQzjQtrwprxGqGdNXwYElfu3prz_DlaV39NOnNzU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
